apiVersion: v1
kind: Namespace
metadata:
  name: llms

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bge-reranker
  namespace: llms
  labels:
    app: bge-reranker
spec:
  replicas: 1 # 副本数量
  selector:
    matchLabels:
      app: bge-reranker
  template:
    metadata:
      labels:
        app: bge-reranker
    spec:
      containers:
      - name: bge-reranker
        image: llama.cpp:server_cpu # 使用的镜像
        imagePullPolicy: IfNotPresent # 镜像拉取策略
        command: ["./llama-server", "--reranking"]
        env:
        - name: LLAMA_ARG_MODEL
          value: "/models/bge-reranker-v2-m3-Q5_K_M.gguf"
        - name: LLAMA_ARG_PORT
          value: "8000"
        - name: LLAMA_ARG_UBATCH
          value: "4096"
        - name: LLAMA_ARG_HOST  
          value: "0.0.0.0"
        - name: LLAMA_ARG_N_PARALLEL
          value: "10"
        - name: LLAMA_ARG_N_PREDICT
          value: "4096"
        resources:
          requests:
            memory: "64Mi"  # 请求的内存大小
            cpu: "250m"     # 请求的 CPU 大小（以毫核为单位）
          limits:
            memory: "4Gi" # 限制的内存大小
            cpu: "2000m"
        ports:
        - containerPort: 8000 # 容器暴露的端口

        volumeMounts:
        - mountPath: /dev/shm
          name: cache-volume
        - mountPath: /models
          name: models-volume
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"   # 设置合理值，以防止占用过多导致集群崩溃
        
      - name: models-volume
        hostPath:
          path: /data/models  # 宿主机上的实际路径
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: bge-reranker
  namespace: llms
spec:
  selector:
    app: bge-reranker  # 确保这与 Deployment 中 Pod 的标签相匹配
  ports:
    - protocol: TCP
      port: 8000  # Service 监听的端口
      targetPort: 8000  # Pod 内应用程序监听的端口
      nodePort: 30001  # Node 上开放的端口
  type: NodePort  # Service 类型设置为 NodePort

---
# 如果希望使用ingress，则需要安装Nginx Ingress Controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bge-reranker
  annotations:
    # 根据需要添加 Nginx Ingress 控制器的特定注解
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # 确保这与您的 Nginx Ingress 控制器的类名匹配
  rules:
  - host: 192.168.31.200 # 替换为您的域名或通配符域名
    http:
      paths:
      - path: /reranker
        pathType: Prefix
        backend:
          service:
            name: bge-reranker
            port:
              number: 8000